import { test, expect } from '@playwright/test';
const key = 'outpost-09-expedition-v1';
test('build, spend orders, advance a cycle, and restore on reload', async ({ page }) => {
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('/');
  await expect(page.locator('[data-tile]')).toHaveCount(108);
  await page.locator('[data-tile="55"]').click();
  await page.locator('[data-build="turret"]').click();
  await expect(page.locator('.tile-identity h3')).toHaveText('Sentry turret');
  await expect(page.locator('.orders strong')).toHaveText('2 / 3');
  await page.locator('[data-action="charge"]').click();
  await expect(page.locator('.signal-copy .section-label')).toContainText('20%');
  await page.locator('[data-command="end"]').click();
  await expect(page.locator('.cycle-stat strong')).toHaveText('02 / 10');
  await page.reload();
  await expect(page.locator('.cycle-stat strong')).toHaveText('02 / 10');
  await expect(page.locator('.tile-identity h3')).toHaveText('Sentry turret');
  expect(errors).toEqual([]);
});
test('help, guide, mission log, pause, sound, and restart work', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'How to play', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.keyboard.press('Escape');
  await page.locator('.map-tabs [data-command="guide"]').click();
  await expect(page.locator('.guide')).toBeVisible();
  await page.locator('.guide [data-command="map"]').click();
  await page.getByRole('button', { name: 'View mission log' }).click();
  await expect(page.locator('.full-log')).toContainText('Touchdown confirmed');
  await page.getByRole('button', { name: 'Close dialog' }).click();
  await page.getByRole('button', { name: 'Enable sound' }).click();
  await expect(page.getByRole('button', { name: 'Mute', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: 'Pause expedition' }).click();
  await expect(page.getByRole('dialog')).toContainText('The universe can wait.');
  await page.keyboard.press('Escape');
  await page.locator('[data-command="end"]').click();
  await page.getByRole('button', { name: 'New expedition', exact: true }).click();
  await page.getByRole('button', { name: 'Keep playing' }).click();
  await expect(page.locator('.cycle-stat strong')).toHaveText('02 / 10');
  await page.getByRole('button', { name: 'New expedition', exact: true }).click();
  await page.getByRole('button', { name: 'Start expedition' }).click();
  await expect(page.locator('.cycle-stat strong')).toHaveText('01 / 10');
});
test('keyboard map navigation and dialog focus remain accessible', async ({ page }) => {
  await page.goto('/');
  await page.locator('[data-tile="54"]').focus();
  await page.keyboard.press('ArrowRight');
  await expect(page.locator('[data-tile="55"]')).toBeFocused();
  await expect(page.locator('.coord')).toHaveText('H05');
  await page.keyboard.press('?');
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.keyboard.press('Shift+Tab');
  await expect(page.locator('.modal .primary')).toBeFocused();
});
test('corrupt saves recover safely and blocked storage remains playable', async ({ page }) => {
  await page.addInitScript(key => localStorage.setItem(key, '{broken'), key);
  await page.goto('/');
  await expect(page.locator('.cycle-stat strong')).toHaveText('01 / 10');
  const context = await page.context().browser().newContext();
  const blocked = await context.newPage();
  await blocked.addInitScript(() => { Storage.prototype.setItem = () => { throw Error('Storage blocked'); }; });
  await blocked.goto('http://127.0.0.1:5174');
  await expect(blocked.locator('footer')).toContainText('SAVING UNAVAILABLE');
  await blocked.locator('[data-command="end"]').click();
  await expect(blocked.locator('.cycle-stat strong')).toHaveText('02 / 10');
  await context.close();
});
for (const width of [1440, 1024, 768, 390, 320]) test(`layout fits a ${width}px screen`, async ({ page }, testInfo) => {
  await page.setViewportSize({ width, height: 1000 });
  await page.goto('/');
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
  expect(overflow).toBe(false);
  await page.locator('[data-tile="55"]').click();
  await expect(page.locator('[data-build="turret"]')).toBeEnabled();
  await page.screenshot({ path: testInfo.outputPath(`outpost-${width}.png`), fullPage: true });
});
